const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const validId=s=>/^[a-f0-9-]{36}$/.test(s);
const mediaTypes=['video/mp4','video/webm','video/quicktime','image/jpeg','image/png','image/webp','image/gif'];
const hash=async t=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const read=async(b,k)=>{const o=await b.get(k);return o?o.json():null};
const put=(b,k,v)=>b.put(k,JSON.stringify(v),{httpMetadata:{contentType:'application/json'}});
const sessionKey=async r=>{const token=(r.headers.get('cookie')||'').match(/(?:^|;\s*)mauzer_session=([a-f0-9]{64})(?:;|$)/)?.[1];return token?'sessions/'+await hash(token):null};
async function auth(r,b){const k=await sessionKey(r),s=k&&await read(b,k);return !!s&&s.expires>Date.now()}
function metadata(v){const title=String(v.title||'').trim(),description=String(v.description||'').trim(),playlist=String(v.playlist||'').trim(),start=Number(v.start||0),end=Number(v.end||0),duration=Number(v.duration||0);if(!title||title.length>120||description.length>3000||playlist.length>60)fail('Перевір назву, опис і плейлист.');if(![start,end,duration].every(Number.isFinite)||start<0||end<0||duration<0||duration>86400||(duration>0&&(end<=start||end>duration+.5)))fail('Некоректні межі відео.');const aliases=Array.isArray(v.aliases)?v.aliases.map(x=>String(x).trim()).filter(Boolean).slice(0,12):['-MaUz3r-','_MaUza_'];const events=Array.isArray(v.events)?v.events.slice(0,500).map(e=>{const timestamp=Number(e.timestamp),confidence=e.confidence==null?null:Number(e.confidence),type=['KILL','DEATH','ASSIST'].includes(e.type)?e.type:'KILL',signature=String(e.signature||'').replace(/[^a-z0-9:_ -]/gi,'').slice(0,240);if(!Number.isFinite(timestamp)||timestamp<0||timestamp>duration+.5)fail('Некоректний час події.');if(confidence!=null&&(!Number.isFinite(confidence)||confidence<0||confidence>1))fail('Некоректна впевненість події.');return {id:/^[a-f0-9-]{8,64}$/i.test(String(e.id||''))?String(e.id):crypto.randomUUID(),type,timestamp,confidence,alias:aliases.includes(String(e.alias||''))?String(e.alias):null,signature,source:e.source==='ocr'?'ocr':'manual'}}):[];const analysisStatus=['idle','processing','ready','error'].includes(v.analysisStatus)?v.analysisStatus:'idle';return {title,description,playlist,start,end,duration,aliases,events,analysisStatus}}
async function route(r,env){const u=new URL(r.url),p=u.pathname,b=env.BUCKET;
 if(!p.startsWith('/api/')&&!p.startsWith('/media/')){const a=ASSETS[p==='/'?'/index.html':p];if(!a)return new Response('Not found',{status:404});return new Response(Uint8Array.from(atob(a.data),c=>c.charCodeAt(0)),{headers:{'Content-Type':a.type,'Cache-Control':p==='/'?'no-cache':'public,max-age=3600','X-Content-Type-Options':'nosniff'}})}
 if(!b)fail('Сховище зараз недоступне. Спробуй пізніше.',503);
 if(!['GET','HEAD'].includes(r.method)){const origin=r.headers.get('origin');if(!origin||![u.origin,'https://mauzer-highlights.danya-voloshko.chatgpt.site'].includes(origin))fail('Недозволений запит.',403)}
 if(p==='/api/session'&&r.method==='GET')return json({admin:await auth(r,b)});
 if(p==='/api/login'&&r.method==='POST'){const k='attempts/'+await hash(r.headers.get('oai-authenticated-user-id')||r.headers.get('cf-connecting-ip')||'anonymous'),previous=await read(b,k),n=previous&&previous.until>Date.now()?previous:{count:0,until:Date.now()+60000};if(n.count>=8)fail('Забагато спроб. Спробуй через хвилину.',429);const v=await r.json();if(String(v.password)!==String(env.MAUZER_PASSWORD||'123')){await put(b,k,{...n,count:n.count+1});fail('Неправильний пароль.',401)}await b.delete(k);const token=Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');await put(b,'sessions/'+await hash(token),{expires:Date.now()+43200000});return json({admin:true},200,{'Set-Cookie':'mauzer_session='+token+'; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200'})}
 if(p==='/api/logout'&&r.method==='POST'){const k=await sessionKey(r);if(k)await b.delete(k);return json({ok:true},200,{'Set-Cookie':'mauzer_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'})}
 if(p==='/api/highlights'&&r.method==='GET'){let cursor,items=[];do{const page=await b.list({prefix:'highlights/',cursor,limit:500});for(let i=0;i<page.objects.length;i+=20)items.push(...(await Promise.all(page.objects.slice(i,i+20).map(o=>read(b,o.key)))).filter(Boolean));cursor=page.truncated?page.cursor:undefined}while(cursor);return json({items:items.sort((a,c)=>c.createdAt-a.createdAt)})}
 if(p.startsWith('/media/')&&['GET','HEAD'].includes(r.method)){const key=p.slice(7);if(!/^[a-f0-9-]{36}(?:-thumb)?$/.test(key))fail('Не знайдено.',404);const h=await b.head('media/'+key);if(!h)fail('Файл не знайдено.',404);let opts={},status=200,rangeHeader=null;const range=r.headers.get('range');if(range){const m=/^bytes=(\d*)-(\d*)$/.exec(range);if(!m||(!m[1]&&!m[2]))return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+h.size}});const start=m[1]?Number(m[1]):Math.max(0,h.size-Number(m[2])),end=m[1]?(m[2]?Math.min(Number(m[2]),h.size-1):h.size-1):h.size-1;if(start>end||start>=h.size)return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+h.size}});opts={range:{offset:start,length:end-start+1}};status=206;rangeHeader='bytes '+start+'-'+end+'/'+h.size}const o=r.method==='HEAD'?h:await b.get('media/'+key,opts),headers={'Content-Type':h.httpMetadata?.contentType||'application/octet-stream','Accept-Ranges':'bytes','Cache-Control':'private,max-age=3600','X-Content-Type-Options':'nosniff','Content-Length':String(opts.range?.length||h.size)};if(rangeHeader)headers['Content-Range']=rangeHeader;return new Response(r.method==='HEAD'?null:o.body,{status,headers})}
 if(!await auth(r,b))fail('Увійди як Маюзер.',401);
 if(p.startsWith('/api/upload/')&&r.method==='PUT'){const key=p.slice(12);if(!/^[a-f0-9-]{36}(?:-thumb)?$/.test(key))fail('Некоректний файл.');const type=r.headers.get('content-type')?.split(';')[0],size=Number(r.headers.get('content-length'));if(!mediaTypes.includes(type)||!size||size>90*1024*1024||(key.endsWith('-thumb')&&(!type.startsWith('image/')||size>2*1024*1024)))fail('Підтримуються фото та відео до 90 МБ.');await b.put('media/'+key,r.body,{httpMetadata:{contentType:type}});return json({ok:true})}
 if(p==='/api/highlights'&&r.method==='POST'){const v=await r.json();if(!validId(v.id))fail('Некоректний ідентифікатор.');const h=await b.head('media/'+v.id);if(!h)fail('Спершу завантаж файл.');const data=metadata(v);if(h.httpMetadata.contentType.startsWith('video/')&&!data.duration)fail('Не визначено тривалість відео.');const item={id:v.id,...data,type:h.httpMetadata.contentType,createdAt:Date.now(),thumbnail:!!await b.head('media/'+v.id+'-thumb')};await put(b,'highlights/'+v.id,item);return json(item,201)}
 if(p.startsWith('/api/highlights/')){const id=p.slice(16);if(!validId(id))fail('Некоректний ідентифікатор.');const item=await read(b,'highlights/'+id);if(!item)fail('Момент не знайдено.',404);if(r.method==='PATCH'){const v=await r.json(),next={...item,...metadata({...v,duration:item.duration}),updatedAt:Date.now(),thumbnail:!!await b.head('media/'+id+'-thumb')};await put(b,'highlights/'+id,next);return json(next)}if(r.method==='DELETE'){await b.delete('highlights/'+id);await b.delete(['media/'+id,'media/'+id+'-thumb']);return json({ok:true})}}
 return json({error:'Не знайдено.'},404)
}
export default {async fetch(request,env){try{return await route(request,env)}catch(e){if(!e.status)console.error('Mauzer request failed',e);return json({error:e.status?e.message:'Не вдалося виконати дію. Спробуй ще раз.'},e.status||503)}}};
